In [ ]:
import pandas as pd
from datetime import datetime

In [ ]:
# Load CSV files
positive_cases = pd.read_csv('POSITIVE_GROUP_FINAL.csv', parse_dates=['study_date_anon', 'diagnosed_date_anon'])
negative_cases = pd.read_csv('NEGATIVE_GROUP_FINAL.csv', parse_dates=['study_date_anon'])

In [ ]:
negative_cases.rename(columns={'empi_anon': 'patient_id', 'acc_anon': 'exam_id', 'ViewPosition':'view'}, inplace=True)

In [ ]:
display(positive_cases)

,patient_id,exam_id,diagnosed_date_anon,procdate_anon,total_L_find,total_R_find,Label,study_date_anon,ImageLateralityFinal,view,...,WindowWidth,has_pix_array,category,VOILUTFunction,WindowCenterWidthExplanation,diagnosed_date_anon_year,study_date_year,Time_to_Cancer_Years,time_to_cancer_group,file_path_dcm
0,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,CC,...,4096.0,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...
1,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,4096.0,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...
2,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,4096.0,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...
3,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,CC,...,4096.0,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...
4,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,MLO,...,4096.0,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085,99868531,8969515521433877,2019-06-07,NaN,NaN,NaN,Non-Cancer,2019-04-01,R,MLO,...,4096.0,False,no image,NaN,NaN,2019,2019,0,BC 1Y,/storage2/images/cohort_1/99868531/1.2.849.113...
3086,99868531,9090933158477514,2019-06-07,NaN,NaN,NaN,Non-Cancer,2015-06-21,R,MLO,...,4096.0,False,no image,NaN,NaN,2019,2015,4,BC 4Y,/storage2/images/cohort_1/99868531/1.2.840.113...
3087,99868531,9090933158477514,2019-06-07,NaN,NaN,NaN,Non-Cancer,2015-06-21,R,CC,...,4096.0,False,no image,NaN,NaN,2019,2015,4,BC 4Y,/storage2/images/cohort_1/99868531/1.2.840.113...
3088,99868531,9161828304530939,2019-06-07,NaN,NaN,NaN,Non-Cancer,2016-02-01,R,CC,...,4096.0,False,no image,NaN,NaN,2019,2016,3,BC 3Y,/storage2/images/cohort_1/99868531/1.2.846.113...
3089,99868531,9161828304530939,2019-06-07,NaN,NaN,NaN,Non-Cancer,2016-02-01,R,MLO,...,4096.0,False,no image,NaN,NaN,2019,2016,3,BC 3Y,/storage2/images/cohort_1/99868531/1.2.846.113...

In [ ]:
display(negative_cases)

,patient_id,exam_id,anon_dicom_path,desc,ProtocolName,asses,path_severity,study_date_anon,side,ImageLateralityFinal,bside,view,match_level,num_roi,ROI_coords
0,10093833,2030506250163251,/storage2/images/cohort_2/10093833/1.2.846.113...,MG Screening Bilateral w/CAD,L CC,N,NaN,2013-06-21,L,L,NaN,CC,[],0,()
1,10093833,2030506250163251,/storage2/images/cohort_2/10093833/1.2.846.113...,MG Screening Bilateral w/CAD,R CC,N,NaN,2013-06-21,R,R,NaN,CC,[],0,()
2,10093833,2030506250163251,/storage2/images/cohort_2/10093833/1.2.846.113...,MG Screening Bilateral w/CAD,L MLO,N,NaN,2013-06-21,L,L,NaN,MLO,[],0,()
3,10093833,2030506250163251,/storage2/images/cohort_2/10093833/1.2.846.113...,MG Screening Bilateral w/CAD,R MLO,N,NaN,2013-06-21,R,R,NaN,MLO,[],0,()
4,10093833,2500827897014911,/storage2/images/cohort_2/10093833/1.2.842.113...,MG Screening Bilateral w/CAD,L CC,N,NaN,2014-07-02,L,L,NaN,CC,[],0,()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49350,99986224,8107409307566891,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screen Bilat w/Tomo/CAD Stnd Protocol,R MLO ComboHD,N,NaN,2018-05-22,R,R,NaN,MLO,[],0,()
49351,99986224,9061973132112039,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,L CC,N,NaN,2013-04-10,L,L,NaN,CC,[],0,()
49352,99986224,9061973132112039,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,R CC,N,NaN,2013-04-10,R,R,NaN,CC,[],0,()
49353,99986224,9061973132112039,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,L MLO,N,NaN,2013-04-10,L,L,NaN,MLO,[],0,()
49354,99986224,9061973132112039,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,R MLO,N,NaN,2013-04-10,R,R,NaN,MLO,[],0,()

In [ ]:
# For positive cases
def calculate_positive_followup(row):
    # Compute difference in years between the exam date and cancer diagnosis date
    return (row['diagnosed_date_anon'] - row['study_date_anon']).days / 365.25

positive_cases['years_last_followup'] = positive_cases.apply(calculate_positive_followup, axis=1)
positive_cases['years_last_followup'] = positive_cases['years_last_followup'].astype(int)
# For negative cases
def calculate_negative_followup(patient_df):
    # Determine the latest exam date for each patient
    latest_date = patient_df['study_date_anon'].max()
    # Compute difference in years between the exam date and the latest available date
    patient_df['years_last_followup'] = (latest_date - patient_df['study_date_anon']).dt.days / 365.25
    patient_df['years_last_followup'] = patient_df['years_last_followup'].astype(int)
    return patient_df

In [ ]:
display(positive_cases)

,patient_id,exam_id,diagnosed_date_anon,procdate_anon,total_L_find,total_R_find,Label,study_date_anon,ImageLateralityFinal,view,...,has_pix_array,category,VOILUTFunction,WindowCenterWidthExplanation,diagnosed_date_anon_year,study_date_year,Time_to_Cancer_Years,time_to_cancer_group,file_path_dcm,years_last_followup
0,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,CC,...,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1
1,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1
2,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1
3,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,CC,...,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...,0
4,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,MLO,...,False,no image,NaN,NaN,2014,2013,1,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085,99868531,8969515521433877,2019-06-07,NaN,NaN,NaN,Non-Cancer,2019-04-01,R,MLO,...,False,no image,NaN,NaN,2019,2019,0,BC 1Y,/storage2/images/cohort_1/99868531/1.2.849.113...,0
3086,99868531,9090933158477514,2019-06-07,NaN,NaN,NaN,Non-Cancer,2015-06-21,R,MLO,...,False,no image,NaN,NaN,2019,2015,4,BC 4Y,/storage2/images/cohort_1/99868531/1.2.840.113...,3
3087,99868531,9090933158477514,2019-06-07,NaN,NaN,NaN,Non-Cancer,2015-06-21,R,CC,...,False,no image,NaN,NaN,2019,2015,4,BC 4Y,/storage2/images/cohort_1/99868531/1.2.840.113...,3
3088,99868531,9161828304530939,2019-06-07,NaN,NaN,NaN,Non-Cancer,2016-02-01,R,CC,...,False,no image,NaN,NaN,2019,2016,3,BC 3Y,/storage2/images/cohort_1/99868531/1.2.846.113...,3
3089,99868531,9161828304530939,2019-06-07,NaN,NaN,NaN,Non-Cancer,2016-02-01,R,MLO,...,False,no image,NaN,NaN,2019,2016,3,BC 3Y,/storage2/images/cohort_1/99868531/1.2.846.113...,3

In [ ]:

negative_cases = negative_cases.groupby('patient_id').apply(calculate_negative_followup)

# Combine datasets if needed
all_cases = pd.concat([positive_cases, negative_cases], ignore_index=True)

<ipython-input-8-2326b4459596>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  negative_cases = negative_cases.groupby('patient_id').apply(calculate_negative_followup)

In [ ]:
display(all_cases)

,patient_id,exam_id,diagnosed_date_anon,procdate_anon,total_L_find,total_R_find,Label,study_date_anon,ImageLateralityFinal,view,...,time_to_cancer_group,file_path_dcm,years_last_followup,anon_dicom_path,desc,asses,path_severity,side,bside,match_level
0,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,CC,...,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10119504,5579010047669510,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-01-19,L,MLO,...,BC 1Y,/storage2/images/cohort_2/10119504/1.2.846.113...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,CC,...,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10119504,9436120411494617,2014-02-10,NaN,NaN,NaN,Non-Cancer,2013-06-29,L,MLO,...,BC 1Y,/storage2/images/cohort_2/10119504/1.2.847.113...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52440,99986224,8107409307566891,NaT,NaN,NaN,NaN,NaN,2018-05-22,R,MLO,...,NaN,NaN,0,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screen Bilat w/Tomo/CAD Stnd Protocol,N,NaN,R,NaN,[]
52441,99986224,9061973132112039,NaT,NaN,NaN,NaN,NaN,2013-04-10,L,CC,...,NaN,NaN,5,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,N,NaN,L,NaN,[]
52442,99986224,9061973132112039,NaT,NaN,NaN,NaN,NaN,2013-04-10,R,CC,...,NaN,NaN,5,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,N,NaN,R,NaN,[]
52443,99986224,9061973132112039,NaT,NaN,NaN,NaN,NaN,2013-04-10,L,MLO,...,NaN,NaN,5,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,N,NaN,L,NaN,[]
52444,99986224,9061973132112039,NaT,NaN,NaN,NaN,NaN,2013-04-10,R,MLO,...,NaN,NaN,5,/storage2/images/cohort_1/99986224/1.2.843.113...,MG Screening Bilateral w/CAD,N,NaN,R,NaN,[]

In [ ]:
# Save to CSV
all_cases.to_csv('combined_cases_with_followup.csv', index=False)